language: go
os: linux
go:
  - 1.15
  - 1.16
script:
  - go test -v ./...
deploy:
  - provider: script
    cleanup: false
    script: curl -sL https://git.io/goreleaser | bash
    on:
      go: 1.16
      tags: true